---
- name: Copy file Get Resource RAM, CPU to other hosts
  copy: 
    src=monitoring-resource.sh 
    dest=/root/
    mode: 0755

#- name: Create cronjob get resource RAM, CPU
#  cron:
#   name="Get resource RAM, CPU"
#   user="root"
#   minute: 0,15,45
#   hour: "*"
#   day: "*"
#   month: "*"
#   weekday: "*"   
#   job="/root/monitoring-resource.sh"

#- name: Fetch file Get Resource RAM, CPU from other hosts
#  run_once: yes
#  fetch: 
#    src=/root/VMware-* 
#    dest=/root/VMWARE 
#    flat=yes