---
- name: Copy file Get Resource RAM, CPU to other hosts
  copy: 
    src: monitoring-resource.sh 
    dest: /root/
    mode: 0755

- name: Create cronjob get resource RAM, CPU
  cron:
   name: "Get resource RAM, CPU"
   user: "root"
   minute: "*/1"
   hour: "*"
   day: "*"
   month: "*"
   weekday: "*"   
   job: "/root/monitoring-resource.sh"

- name: Fetch file Get Resource RAM, CPU from other hosts
  run_once: yes
  fetch: 
    src: /root/VMware-VMware-Tier1-4c-8g-100ssd-0.5GHz
    dest: /root/VMWARE 
    flat: yes