---
- name: Copy file Get Resource RAM, CPU to other hosts
  copy: 
    src: monitoring-resource.sh 
    dest: /root/
    mode: 0755

- name: Create cronjob get resource RAM, CPU
  cron:
   name: "Get resource RAM, CPU"
   user: "root"
   minute: "*/1"
   hour: "*"
   day: "*"
   month: "*"
   weekday: "*"   
   job: "/root/monitoring-resource.sh"

- name: Get file Resource RAM, CPU
  shell: ls -lrt /root/ |grep VMware-Tier* | awk '{print $9}'
  register: files_to_fetch

- name: Fetch file Get Resource RAM, CPU from other hosts
  run_once: yes
  fetch: 
    src: /root/{{ files_to_fetch }}
    dest: /VMWARE/{{ files_to_fetch }}
    flat: yes