---
# defaults file for geekbench5

# DEVS: Update this version as appropriate.
# MAYBE/2018-12-26: Add version watcher for Geekbench.
#   https://www.geekbench.com/download/linux/
geekbench5_app_version: '5.2.3'
geekbench5_app_prgname: 'Geekbench-{{ geekbench5_app_version }}-Linux'
geekbench5_app_archive: "{{ geekbench5_app_prgname }}.tar.gz"
# 2018-12-13: The latest download is at, e.g.,
#   http://cdn.geekbench.com/Geekbench-5.2.3-Linux.tar.gz
geekbench5_app_downurl: "http://cdn.geekbench.com/{{ geekbench5_app_archive }}"

# DEVS: You'll find files on the host under:
#   ~/benchmark/geekbench5/
geekbench5_working_dir: "{{ ansible_env.HOME }}/benchmark/geekbench5"

geekbench5_working_tar: "{{ geekbench5_working_dir }}/{{ geekbench5_app_archive }}"
geekbench5_program_dir: "{{ geekbench5_working_dir }}/{{ geekbench5_app_prgname }}"
geekbench5_results_lns: "{{ geekbench5_working_dir }}/{{ ansible_hostname }}-geekbench5-results.txt"

