---
- name: Benchmark with APACHE 
  command: phoronix-test-suite batch-benchmark pts/apache-2.0.0  
- name: Benchmark with NGINX 
  command: phoronix-test-suite batch-benchmark pts/nginx-2.0.0
- name: Benchmark with SYSBENCH 
  command: phoronix-test-suite batch-benchmark pts/sysbench-1.1.0
# - name: Benchmark with DATABASE 
#   command: phoronix-test-suite batch-benchmark pts/mysqlslap-1.2.0  
- name: Benchmark with COMPRESSION 
  command: phoronix-test-suite batch-benchmark pts/compress-7zip-1.7.1
  register: phoronix_output
- set_fact:
    phoronix_results_url: "{{ phoronix_output.stdout_lines[-1] | trim }}"
- name: Copy phoronix output to phoronix stdout file
  shell: echo "{{ phoronix_results_url }}" >> "/var/lib/phoronix-test-suite/test-results/{{ ansible_hostname }}-phoronix-results.txt"

- name: Tell user where to find phoronix results
  debug:
    msg: >
          You'll find the phoronix results here!

            {{ phoronix_results_url }}
