---
- name: Install Database 
  command: phoronix-test-suite batch-install dungta/idc-mariadb-test
- name: Benchmark Database 
  command: phoronix-test-suite batch-benchmark dungta/idc-mariadb-test
  register: phoronix_output
- set_fact:
    phoronix_results_url: "{{ phoronix_output.stdout_lines[-1] | trim }}"
- name: Copy phoronix output to phoronix stdout file
  shell: echo "{{ phoronix_results_url }}" >> "/var/lib/phoronix-test-suite/test-results/{{ ansible_hostname }}-phoronix-results.txt"

- name: Tell user where to find phoronix results
  debug:
    msg: >
          You'll find the phoronix results here!

            {{ phoronix_results_url }}
