---
#- name: Benchmark with APACHE 
#  command: phoronix-test-suite batch-benchmark pts/apache  

#- name: Benchmark with NGINX 
#  command: phoronix-test-suite batch-benchmark pts/nginx

- name: Benchmark with SYSBENCH 
  command: phoronix-test-suite batch-benchmark pts/sysbench

- name: 'Get CPU USAGE'
  shell: |
    top -b -n2 -p 1 | fgrep "Cpu(s)" | tail -1 | awk -F'id,' -v prefix="$prefix" '{ split($1, vs, ","); v=vs[length(vs)]; sub("%", "", v); printf "%s%.1f%%\n", prefix, 100 - v }'
  register: cpuusage
- name: 'Print CPU USAGE'
  debug:
    msg:
      - --------------------------------
      - CPU % Usage = {{ cpuusage.stdout }}
      - ---------------------------------
- name: 'Get CPU LOAD'
  shell: |
    cat /proc/loadavg |awk '{print $1}'
  register: cpuload
- name: 'Print CPU LOAD'
  debug:
    msg:
      - ------------------------
      - CPU Load = {{ cpuload.stdout }}
      - ------------------------
- name: 'Print CPU LOAD'
  shell: |
    free -m | awk 'NR==2{printf "Memory Usage: %s/%sMB (%.2f%%)\n", $3,$2,$3*100/$2 }'
  register: ramusage
- name: 'Print RAM USAGE'
  debug:
    msg:
      - ----------------------------------
      - RAM Usage = {{ ramusage.stdout }}
      - ----------------------------------

- name: Benchmark with COMPRESSION 
  command: phoronix-test-suite batch-benchmark pts/compress-7zip

- name: 'Get CPU USAGE'
  shell: |
    top -b -n2 -p 1 | fgrep "Cpu(s)" | tail -1 | awk -F'id,' -v prefix="$prefix" '{ split($1, vs, ","); v=vs[length(vs)]; sub("%", "", v); printf "%s%.1f%%\n", prefix, 100 - v }'
  register: cpuusage
- name: 'Print CPU USAGE'
  debug:
    msg:
      - --------------------------------
      - CPU % Usage = {{ cpuusage.stdout }}
      - --------------------------------
- name: 'Get CPU LOAD'
  shell: |
    cat /proc/loadavg |awk '{print $1}'
  register: cpuload
- name: 'Print CPU LOAD'
  debug:
    msg:
      - ------------------------
      - CPU Load = {{ cpuload.stdout }}
      - ------------------------
- name: 'Print CPU LOAD'
  shell: |
    free -m | awk 'NR==2{printf "Memory Usage: %s/%sMB (%.2f%%)\n", $3,$2,$3*100/$2 }'
  register: ramusage
- name: 'Print RAM USAGE'
  debug:
    msg:
      - ----------------------------------
      - RAM Usage = {{ ramusage.stdout }}
      - ----------------------------------

#- name: Benchmark with DATABASE 
#  command: phoronix-test-suite batch-benchmark pts/mysqlslap
#  register: phoronix_output

#- set_fact:
#    phoronix_results_url: "{{ phoronix_output.stdout_lines[-1] | trim }}"

- name: Copy phoronix output to phoronix stdout file
  shell: echo "{{ phoronix_results_url }}" >> "/var/lib/phoronix-test-suite/test-results/{{ ansible_hostname }}-phoronix-results.txt"

- name: Tell user where to find phoronix results
  debug:
    msg: >
          You'll find the phoronix results here!

            {{ phoronix_results_url }}
