---
- name: Benchmark with Apache Nginx Mysqlslap Sysbench Compress-zip 
  command: phoronix-test-suite batch-benchmark pts/sysbench
  #pts/apache pts/nginx pts/sysbench pts/compress-7zip pts/mysqlslap
  register: phoronix_output

- set_fact:
    phoronix_results_url: "{{ phoronix_output.stdout_lines[-1] | trim }}"

- name: Copy phoronix output to phoronix stdout file
  shell: echo "{{ phoronix_results_url }}" >> "/var/lib/phoronix-test-suite/test-results/"

- name: Tell user where to find phoronix results
  debug:
    msg: >
          You'll find the phoronix results here!

            {{ phoronix_results_url }}
