---
- name: install epel-release
  yum:
    name: epel-release
    state: latest
- name: update
  yum:
    name: '*'
    state: latest
- name: install bzip2
  yum:
    name: bzip2
    state: latest
- name: install phoronix-test-suite.noarch
  yum:
    name: phoronix-test-suite.noarch
    state: latest
- name: install unzip
  yum:
    name: unzip
    state: latest
- name: install python-lxml.x86_64 for managing xml
  yum:
    name: python-lxml.x86_64
    state: latest
- name: install p7zip
  yum:
    name: p7zip
    state: latest
- name: install p7zip-plugins
  yum:
    name: p7zip-plugins
    state: latest
- name: install liberation-sans-fonts.noarch for result-file-to-pdf
  yum:
    name: liberation-sans-fonts.noarch
    state: latest
- name: install php-cli
  yum:
    name: php-cli
    state: latest
- name: install php-xml
  yum:
    name: php-xml
    state: latest
- name: install php-json
  yum:
    name: php-json
    state: latest
- name: install golang
  yum:
    name: golang
    state: latest
- name: install htop
  yum:
    name: htop
    state: latest
- name: install vim
  yum:
    name: vim
    state: latest
- name: install gcc, gcc-c++, autoconf, automake, patch, expat-devel, libtool, libaio-devel, pcre-devel, zlib-devel, cmake, libevent-devel, ncurses-devel, bison, flex, openssl-devel  
  yum:
    name: 
    - gcc
    - gcc-c++
    - autoconf
    - automake
    - patch
    - expat-devel
    - libtool
    - libaio-devel
    - pcre-devel
    - zlib-devel
    - cmake
    - libevent-devel
    - ncurses-devel
    - bison
    - flex
    - openssl-devel
    state: latest
- name: reboot host
  shell: sleep 10 && sync && sync && /usr/sbin/reboot
  async: 300
  poll: 0