---
# Benchmark task: Download geekbench5, run it,
# and open the results in a new browser window.

- name: Ensure the working directory exists
  file: path={{ geekbench5_working_dir }} state=directory

- name: Ensure the results file exists
  file: path={{ geekbench5_results_lns }} state=touch

# MAYBE/2018-12-26: Remove old versions' downloads and unpacked archives.

- name: Stat geekbench5 archive before downloading
  stat: path={{ geekbench5_working_tar }}
  register: geekbench5_archive

- name: Fetch the geekbench5 archive, if necessary
  get_url:
    url: '{{ geekbench5_app_downurl }}'
    dest: "{{ geekbench5_working_dir }}/"
  # Avoid connecting to the CDN server if the file exists locally.
  # (There's a get_url default, `force: no`, that will not download the
  # archive if it has not changed, but it still checks with the server.)
  when: geekbench5_archive.stat.exists == False

- name: Unarchive the geekbench5 archive
  unarchive:
    src: "{{ geekbench5_working_tar }}"
    dest: "{{ geekbench5_working_dir }}/"
    # We could instead download to the master,
    # and unpack to the host, but we downloaded
    # to the host, so tell Ansible to look there.
    remote_src: yes

- name: Benchmark the host! Run geekbench5
  shell: ./geekbench5
  args:
    chdir: "{{ geekbench5_program_dir }}"
  register: geekbench5_output

- set_fact:
    geekbench5_results_url: "{{ geekbench5_output.stdout_lines[-1] | trim }}"

- name: Copy geekbench5 output to geekbench stdout file
  shell: echo "{{ geekbench5_results_url }}" >> "{{ geekbench5_results_lns }}"

- name: Tell user where to find geekbench5 results
  debug:
    msg: >
          You'll find the geekbench5 results here!

            {{ geekbench5_results_url }}

